export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as FAQ } from "./FAQ";
export { default as Fees } from "./Fees";
export { default as KidsClasses } from "./Classes_Kids";
export { default as AdultsClasses } from "./Classes_Adults";
export { default as Groups } from "./Groups";
export { default as Contact } from "./Contact";
export { default as NotFound } from "./NotFound";